In [119]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import random

In [120]:
df = pd.read_csv('Dsata Set.csv')

In [121]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [122]:
df.drop('id',axis=1,inplace=True)
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [123]:
df['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [124]:
df['diagnosis'].replace({'M':1, 'B':-1}, inplace = True)

In [125]:
df['diagnosis'].value_counts()

-1    357
 1    212
Name: diagnosis, dtype: int64

In [126]:
df.isnull().sum()

diagnosis                  0
radius_mean                1
texture_mean               0
perimeter_mean             1
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             1
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             1
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 2
smoothness_worst           0
compactness_worst          0
concavity_worst            1
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [127]:
df['radius_mean'].replace('', np.nan, inplace=True)
df.dropna(subset=['radius_mean'], inplace=True)
df['perimeter_mean'].replace('', np.nan, inplace=True)
df.dropna(subset=['perimeter_mean'], inplace=True)
df['concavity_mean'].replace('', np.nan, inplace=True)
df.dropna(subset=['concavity_mean'], inplace=True)
df['compactness_se'].replace('', np.nan, inplace=True)
df.dropna(subset=['compactness_se'], inplace=True)
df['area_worst'].replace('', np.nan, inplace=True)
df.dropna(subset=['area_worst'], inplace=True)
df['concavity_worst'].replace('', np.nan, inplace=True)
df.dropna(subset=['concavity_worst'], inplace=True)

In [128]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            1        17.99         10.38          122.80     1001.0   
1            1        20.57         17.77          132.90     1326.0   
2            1        19.69         21.25          130.00     1203.0   
3            1        11.42         20.38           77.58      386.1   
4            1        20.29         14.34          135.10     1297.0   
..         ...          ...           ...             ...        ...   
564          1        21.56         22.39          142.00     1479.0   
565          1        20.13         28.25          131.20     1261.0   
566          1        16.60         28.08          108.30      858.1   
567          1        20.60         29.33          140.10     1265.0   
568         -1         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    .

In [129]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [130]:
df.dtypes

diagnosis                    int64
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst

#      PM1

In [55]:
y=df[['diagnosis']]
X=df.loc[0:563,'radius_mean':]
X_train = X.loc[0:377].values
X_test = X.loc[378:563].values
y_train = y.loc[0:377]
y_train = y_train['diagnosis'].tolist()
y_test = y.loc[378:563]
y_test = y_test['diagnosis'].tolist()
print(X_test)

[[1.366e+01 1.515e+01 8.827e+01 ... 1.054e-01 3.387e-01 9.638e-02]
 [1.108e+01 1.883e+01 7.330e+01 ... 2.524e-01 4.154e-01 1.403e-01]
 [1.127e+01 1.296e+01 7.316e+01 ... 1.318e-01 3.343e-01 9.215e-02]
 ...
 [1.120e+01 2.937e+01 7.067e+01 ... 0.000e+00 1.566e-01 5.905e-02]
 [1.522e+01 3.062e+01 1.034e+02 ... 2.356e-01 4.089e-01 1.409e-01]
 [2.092e+01 2.509e+01 1.430e+02 ... 2.542e-01 2.929e-01 9.873e-02]]


# PM2

In [113]:
y=df[['diagnosis']]
X=df.loc[0:563,'radius_mean':]
y_test = y.loc[378:563]
y_test = y_test['diagnosis'].tolist()
X_test = X.loc[378:563].values
train = df.loc[0:377]
train = train.sample(frac = 1)
train.reset_index(inplace=True)
y_train = train[['diagnosis']]
y_train = y_train['diagnosis'].tolist()
X_train = train.loc[0:377,'radius_mean':].values
train

index  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      371         -1       15.190         13.21           97.65      711.8   
1      231         -1       11.320         27.08           71.76      395.7   
2      264          1       17.190         22.07          111.60      928.3   
3      114         -1        8.726         15.83           55.84      230.9   
4      128         -1       15.100         16.39           99.58      674.5   
..     ...        ...          ...           ...             ...        ...   
373     30          1       18.630         25.11          124.80     1088.0   
374    357         -1       13.870         16.21           88.52      593.7   
375    178         -1       13.010         22.22           82.01      526.4   
376     54          1       15.100         22.02           97.26      712.8   
377    326         -1       14.110         12.88           90.03      616.5   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.07963           0.06934        0.033930             0.026570   
1            0.06883           0.03813        0.016330             0.003125   
2            0.09726           0.08995        0.090610             0.065270   
3            0.11500           0.08201        0.041320             0.019240   
4            0.11500           0.18070        0.113800             0.085340   
..               ...               ...             ...                  ...   
373          0.10640           0.18870        0.231900             0.124400   
374          0.08743           0.05492        0.015020             0.020880   
375          0.06251           0.01938        0.001595             0.001852   
376          0.09056           0.07081        0.052530             0.033340   
377          0.09309           0.05306        0.017650             0.027330   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        16.200          15.73           104.50       819.1   
1    ...        12.080          33.75            79.82       452.3   
2    ...        21.580          29.33           140.50      1436.0   
3    ...         9.628          19.62            64.48       284.4   
4    ...        16.110          18.33           105.90       762.6   
..   ...           ...            ...              ...         ...   
373  ...        23.150          34.01           160.50      1670.0   
374  ...        15.110          25.58            96.74       694.4   
375  ...        14.000          29.02            88.18       608.8   
376  ...        18.100          31.69           117.70      1030.0   
377  ...        15.530          18.00            98.40       749.9   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.11260            0.17370         0.136200   
1             0.09203            0.14320         0.108900   
2             0.15580            0.25670         0.388900   
3             0.17240            0.23640         0.245600   
4             0.13860            0.28830         0.196000   
..                ...                ...              ...   
373           0.14910            0.42570         0.613300   
374           0.11530            0.10080         0.052850   
375           0.08125            0.03432         0.007977   
376           0.13890            0.20570         0.271200   
377           0.12810            0.11090         0.053070   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.081780          0.2487                  0.06766  
1                0.020830          0.2849                  0.07087  
2                0.198400          0.3216                  0.07570  
3                0.105000          0.2926                  0.10170  
4                0.142300          0.2590                  0.07779  
..                    ...             ...                      ...  
373              0.184800          0.3444         

# PM3

In [131]:
y=df[['diagnosis']]
X=df.loc[0:563,'radius_mean':]
X=(X-X.mean())/X.std()
X_train = X.loc[0:377].values
X_test = X.loc[378:563].values
y_train = y.loc[0:377]
y_train = y_train['diagnosis'].tolist()
y_test = y.loc[378:563]
y_test = y_test['diagnosis'].tolist()
print(X_test)

[[-0.12568269 -0.95813863 -0.14584112 ... -0.13740632  0.77895723
   0.68148216]
 [-0.86346364 -0.09213212 -0.76666813 ...  2.10561907  2.0172949
   3.11128234]
 [-0.80913094 -1.47350663 -0.77247412 ...  0.26542273  0.70791831
   0.44746452]
 ...
 [-0.82914825  2.38822348 -0.87573793 ... -1.74567078 -2.16108566
  -1.38373734]
 [ 0.32041742  2.6823833   0.4816213  ...  1.84927331  1.91235103
   3.14447633]
 [ 1.9503986   1.38102026  2.12388913 ...  2.13308469  0.03950658
   0.81149196]]


# PM 4

In [266]:
y=df[['diagnosis']]
X=df.loc[0:563,'radius_mean':]
X=X.sample(frac=1, axis=1).reset_index(drop=True)
X_train = X.loc[0:377].values
X_test = X.loc[378:563].values
y_train = y.loc[0:377]
y_train = y_train['diagnosis'].tolist()
y_test = y.loc[378:563]
y_test = y_test['diagnosis'].tolist()
X

radius_se  smoothness_se  texture_se  fractal_dimension_se  area_mean  \
0       1.0950       0.006399      0.9053              0.006193     1001.0   
1       0.5435       0.005225      0.7339              0.003532     1326.0   
2       0.7456       0.006150      0.7869              0.004571     1203.0   
3       0.4956       0.009110      1.1560              0.009208      386.1   
4       0.7572       0.011490      0.7813              0.005115     1297.0   
..         ...            ...         ...                   ...        ...   
553     0.2388       0.008200      2.9040              0.004738      403.5   
554     0.3645       0.007256      1.4920              0.005304      600.4   
555     0.3141       0.007594      3.8960              0.001773      386.0   
556     0.2602       0.004625      1.2050              0.006142      716.9   
557     0.9622       0.006399      1.0260              0.006213     1347.0   

     symmetry_mean  symmetry_se  perimeter_se  smoothness_worst  area_se  ...  \
0           0.2419      0.03003         8.589           0.16220   153.40  ...   
1           0.1812      0.01389         3.398           0.12380    74.08  ...   
2           0.2069      0.02250         4.585           0.14440    94.03  ...   
3           0.2597      0.05963         3.445           0.20980    27.23  ...   
4           0.1809      0.01756         5.438           0.13740    94.44  ...   
..             ...          ...           ...               ...      ...  ...   
553         0.1388      0.01488         1.936           0.12980    16.97  ...   
554         0.1537      0.02080         2.888           0.12410    29.84  ...   
555         0.1060      0.01989         2.041           0.09267    22.81  ...   
556         0.2128      0.02137         2.362           0.14170    22.65  ...   
557         0.2149      0.02057         8.758           0.14070   118.80  ...   

     concavity_se  symmetry_worst  diagnosis_2  concavity_mean  \
0         0.05373          0.4601        10.38         0.30010   
1         0.01860          0.2750        17.77         0.08690   
2         0.03832          0.3613        21.25         0.19740   
3         0.05661          0.6638        20.38         0.24140   
4         0.05688          0.2364        14.34         0.19800   
..            ...             ...          ...             ...   
553       0.05738          0.2112        23.93         0.11120   
554       0.02071          0.2250        27.15         0.04462   
555       0.00000          0.1566        29.37         0.00000   
556       0.07359          0.4089        30.62         0.25500   
557       0.07845          0.2929        25.09         0.31740   

     compactness_se  concave points_mean  smoothness_mean  texture_worst  \
0          0.049040              0.14710          0.11840          17.33   
1          0.013080              0.07017          0.08474          23.41   
2          0.040060              0.12790          0.10960          25.53   
3          0.074580              0.10520          0.14250          26.50   
4          0.024610              0.10430          0.10030          16.67   
..              ...                  ...              ...            ...   
553        0.029820              0.04105          0.09261          37.16   
554        0.026780              0.04304          0.09929          33.17   
555        0.008878              0.00000          0.07449          38.30   
556        0.048440              0.09429          0.10480          42.79   
557        0.043100              0.14740          0.10990          29.41   

     radius_worst  radius_mean  
0           25.38        17.99  
1           24.99        20.57  
2           23.57        19.69  
3           14.91        11.42  
4           22.54        20.29  
..            ...          ...  
553         12.48        11.51  
554         15.30        14.05  
555         11.92        11.20  
556         17.52        15.22  
557         24.29        2

In [132]:
w=[0]*30
print(w)
epoch = 10500

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [133]:
for j in range(epoch):
    for i in range(len(y_train)):
        if (y_train[i]*(X_train[i].dot(w))<=0):
            w=w+y_train[i]*X_train[i]
        elif (y_train[i]*(X_train[i].dot(w))>0):
            w=w+0
print(w)        

[ -76.32322551    6.74399027  -20.88113124  -17.37669262   52.65564401
 -108.1489067   -29.32336234   38.232801    -13.11609364   -0.72437238
   64.73028998  -23.8384322   -38.15570456   58.92419638   -8.74540402
   -9.87741289   -6.39341239  111.32421514   30.93679479  -93.52658146
  133.58728807   71.41694934  106.61156703   30.71044036  -11.74583035
   55.91674798   -2.31613456  -22.618051     -7.90122891   75.30271725]


In [134]:
y_pred=[]
for i in range(len(y_test)):
    if((X_test[i].dot(w))>0):
        y_pred.append(1)
    elif((X_test[i].dot(w))<0):
        y_pred.append(-1)
         
print(y_pred)          

[-1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 1, 1, -1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1, -1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 1, -1, -1, 1, -1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 1, 1]


In [136]:
count=0
t=0
recall = 0
precision = 0
for i in range(len(y_test)):
    if (y_test[i]==y_pred[i]==1):
        count=count+1
        t=t+1
    elif(y_test[i]==y_pred[i]==-1):
        count=count+1
    elif(y_pred[i] == 1):
        recall = recall +1
    elif(y_pred[i] == -1):
        precision = precision +1

recall = recall + t
precision = precision +t
print('Accuracy',count/len(y_test))   
print('Recall',t/recall)
print('Precision',t/precision)

Accuracy 0.9333333333333333
Recall 0.8
Precision 0.9230769230769231
